name: Hello-Deploy

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment (staging|prod)'
        required: true
        default: 'staging'

jobs:
  run-hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run hello.py
        run: |
          python3 hello.py
